name: start
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.7.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.2.1
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  font_awesome_flutter: ^10.8.0
  file_picker: ^8.0.5
  url_launcher: ^6.3.1
  flutter_hooks: ^0.20.5
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.2.1
  flutter_launcher_icons: ^0.14.3
  salomon_bottom_bar: ^3.3.2
  flutter_spinkit: ^5.2.1
  flutter_staggered_animations: ^1.1.1
  like_button: ^2.1.0
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  flutter_map_dragmarker: ^7.0.0
  geolocator: ^8.2.1
  flutter_stripe: 10.2.0
  flutter_easyloading: ^3.0.5
  animated_theme_switcher: ^2.0.10
  cached_network_image: ^3.4.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  flutter_3d_controller: ^2.0.3

  #assets_audio_player: ^3.0.8

dependency_overrides:
  stripe_platform_interface: 10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets\profile.jpeg
    - assets\delivery.gif
    - assets\welcome.gif
    - assets\findout.gif
    - assets\login_dec.png

flutter_icons:
  android: true
  image_path: "assets/logo.jpg"
